<template>

    <div class="col-lg-8">

        <header>
            <h2><span class="icon-pages"></span>Explore Topics</h2>
            <p>We did our best to cover all topics related to this product. Each section have number which represent
                number of topic in each category.</p>
        </header>

        <div class="row match-height">
            <div class="col-md-6 col-sm-12">
                <div class="categories-list">
                    <h3><span class="badge">19</span>Competent National Authorities</h3>
                    <ul>
                        <li><a href="single-article.html"> How to use this documentation? </a></li>
                        <li><a href="single-article.html"> How to find topics? </a></li>
                        <li><a href="single-article.html"> What is included and why? </a></li>
                        <li><a href="single-article.html"> Basic knowledge requirments. </a></li>
                        <li><a href="single-article.html"> Getting Started &amp; What is next. </a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-sm-12">
                <div class="categories-list">
                    <h3><span class="badge">19</span>Supplementary Protocol Competent Authorities</h3>
                    <ul>
                        <li><a href="single-article.html"> How to use this documentation? </a></li>
                        <li><a href="single-article.html"> How to find topics? </a></li>
                        <li><a href="single-article.html"> What is included and why? </a></li>
                        <li><a href="single-article.html"> Basic knowledge requirments. </a></li>
                        <li><a href="single-article.html"> Getting Started &amp; What is next. </a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row match-height">
            <div class="col-md-6 col-sm-12">
                <div class="categories-list">
                    <h3><span class="badge">19</span>Biosafety Laws, Regulations, Guidelines and Agreements</h3>
                    <ul>
                        <li><a href="single-article.html"> How to use this documentation? </a></li>
                        <li><a href="single-article.html"> How to find topics? </a></li>
                        <li><a href="single-article.html"> What is included and why? </a></li>
                        <li><a href="single-article.html"> Basic knowledge requirments. </a></li>
                        <li><a href="single-article.html"> Getting Started &amp; What is next. </a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-sm-12">
                <div class="categories-list">
                    <h3><span class="badge">19</span>Countries' Decisions or any other Communications</h3>
                    <ul>
                        <li><a href="single-article.html"> How to use this documentation? </a></li>
                        <li><a href="single-article.html"> How to find topics? </a></li>
                        <li><a href="single-article.html"> What is included and why? </a></li>
                        <li><a href="single-article.html"> Basic knowledge requirments. </a></li>
                        <li><a href="single-article.html"> Getting Started &amp; What is next. </a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row match-height">
            <div class="col-md-6 col-sm-12">
                <div class="categories-list">
                    <h3><span class="badge">19</span>Risk Assessments generated by a regulatory process</h3>
                    <ul>
                        <li><a href="single-article.html"> How to use this documentation? </a></li>
                        <li><a href="single-article.html"> How to find topics? </a></li>
                        <li><a href="single-article.html"> What is included and why? </a></li>
                        <li><a href="single-article.html"> Basic knowledge requirments. </a></li>
                        <li><a href="single-article.html"> Getting Started &amp; What is next. </a></li>
                    </ul>Popular Tags
                </div>
            </div>
            <div class="col-md-6 col-sm-12">
                <div class="categories-list">
                    <h3><span class="badge">19</span>National Biosafety Websites or Databases</h3>
                    <div><i v-show="!articles.length" class="fa fa-spinner fa-spin"></i></div>
                    <ul v-for="(title, index) in articles">
                        <li><a> {{title.title.en}} </a></li>
                        <li class="tag" v-if="title.adminTags != undefined">
                            <span class="tagcloud" v-for="tag in title.adminTags">
                                <a href="#" class="btn btn-mini">{{tag}}</a>
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
     import VueResource from 'https://cdn.jsdelivr.net/npm/vue-resource@1.5.3'; //will be from npm 'vue-resource'
    Vue.use(VueResource)
    export default {
        data:  () => {
            return {
                articles: []
            }
        },
        mounted() {
            var self = this;
            var ag = [];
            var agLimit = [];
            agLimit.push({"$limit" : 20});
            var qs = {
                "ag" : JSON.stringify(agLimit)
            };
            return Vue.http.get('/api/v2017/articles', {params: qs}).then(function (results) {
                if ((results || {}).data && results.data.length > 0) {

                    self.articles = results.data;
                }
            });
        },
        // i18n: { messages:{ en: i18n }} //will be used for locales language
    }
</script> 