import 'app';
import './directives/footer';
import './directives/xuser-notifications-panel';
import './directives/header/branding.html';
import './directives/header/login.js';
import './directives/header/account.html';
import './directives/header/branding.js';
import './directives/header/locale.html';
import './directives/header/xuser-notification-config-service.js';
import './directives/header/xuser-notifications.html';
import './directives/header/account.js';
import './directives/header/locale.js';
import './directives/header/xuser-notifications.js';
import './directives/header/accounts-validation.html';
import './directives/header/header.html';
import './directives/header/xuser-notifications-icon.html';
import './directives/header/accounts-validation.js';
import './directives/header/header.js';
import './directives/header/login.html';
import './directives/header/xuser-notifications-icon.js';
    export default null;

