define(['app',
    './filters/scbd-filters',
    './services/workflows',
    './services/user-notifications',
    './services/socket-io-service',
    './services/generic-service',
    './services/authentication',
    './services/utilities',
    './services/storage',
    './services/mime.type.service',
    './services/locale',
    './services/extended-route',
    './services/apiUrl',
], function() {});