import 'app'; 

    export { default as template } from './record-types.html';
export default ["$scope", "$http", function ($scope, $http, user) {
        
        var _ctrl = this;

        _ctrl.schemas = {};
        _ctrl.schemas.national = [{ 
                schema : 'focalPoint',
                title : 'National Focal Points',
                description : 'Cartagena Protocol on Biosafety (CPB-NFP), Biosafety Clearing-House (BCH-NFP) or Contact points for unintentional transboundary movements and emergency measures (Art. 17)'
            }, { 
                schema : 'authority',
                title : 'Competent National Authority',
                description : 'Competent National Authority (Article 19.2)'
            }, { 
                schema : 'database',
                title : 'National Biosafety Website or Database',
                description : 'National Biosafety Website or Database'
            }, { 
                schema : 'law',
                title : 'Biosafety Law, Regulation, Guidelines and Agreements',
                description : 'Biosafety Law, Regulation, Guidelines & Regional and International Agreements'
            }, { 
                schema : 'decision',
                title : "Country's Decision or any other Communication",
                description : 'Biosafety Law, Regulation, Guidelines & Regional and International Agreements'
            }, { 
                schema : 'nationalRiskAssessment',
                title : "Risk Assessment",
                description : 'Risk Assessment Generated by a Regulatory Process'
            }, { 
                schema : 'cpbNationalReport3',
                title : "Third National Report on the Implementation of the Cartagena Protocol on Biosafety",
                description : 'To be submitted no later than 1st November 2015; see note on National Report page see Frequently Asked Questions FAQ page'
            }, { 
                schema : 'expert',
                title : "Biosafety Expert",
                description : 'Biosafety Expert (Decisions BS-I/4 and BS-IV/4)'
            }, { 
                schema : 'expertAssignment',
                title : "Report on the assignment undertaken by the Biosafety Expert",
                description : 'Report on the assignment undertaken by the Biosafety Expert'
            }
        ];
        
        _ctrl.schemas.reference = [{ 
                schema : 'contact',
                title : 'Contact Details',
                description : 'Contact Details'
            }, { 
                schema : 'organization',
                title : 'Biosafety Organization',
                description : 'Biosafety Organization including Laboratory for detection and identification of LMOs'
            }, { 
                schema : 'resource',
                title : 'Biosafety Information Resource Centre (BIRC)',
                description : 'Biosafety Information Resource Centre (BIRC)	'
            }, { 
                schema : 'independantRiskAssessment',
                title : "Risk Assessment",
                description : 'Risk Assessment Generated by an independent or non-regulatory process'
            }, { 
                schema : 'modifiedOrganism',
                title : "Living Modified Organism (LMO)",
                description : 'Living Modified Organism (LMO)'
            }, { 
                schema : 'dnaSequence',
                title : "Genetic element",
                description : 'Gene and DNA Sequenece'
            }, { 
                schema : 'organism',
                title : "Organism",
                description : 'Organism'
            }
        ];
        
        
        

    }];


